export const CHAT_DIMENSIONS = {
  HEADER_HEIGHT: 57,
  CONNECTION_BANNER_HEIGHT: 41,
  INPUT_AREA_HEIGHT: 73,
  TIMER_BAR_HEIGHT: 41
} as const;

export const POLLING_INTERVALS = {
  SESSION_STATUS: 2000,
  CONNECTION_MONITOR: 2000
} as const;

export const ANIMATION_DURATIONS = {
  SCROLL_DEBOUNCE: 100,
  STORAGE_DEBOUNCE: 500,
  RECONNECT_DELAY: 3000
} as const;
